[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
cache_path  = "cache_forge"
solc = "0.8.20"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
